name: Compile Sketch

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  # Manual trigger
  workflow_dispatch:

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: 'arduino:avr:nano:cpu=atmega328'
          libraries: |
            - name: MAX6675 library
            - name: Easy Nextion Library
            - name: TimerInterrupt_Generic
            - name: ADS1X15
            - source-url: https://github.com/banoz/PSM.Library/archive/refs/heads/main.zip
            - source-url: https://github.com/banoz/HX711/archive/refs/heads/master.zip
          sketch-paths: |
            - 'gaggiuino.ino'
